(() => {
  const d = window.__TITAN_DATA__;
  if (!d) { document.body.innerHTML = '<pre>Missing window.__TITAN_DATA__</pre>'; return; }
  const app = document.getElementById('app');
  const fmtMin = m => `${Math.floor(m/60)}h${String(m%60).padStart(2,'0')}m`;
  const pct = (v,t) => Math.round(v/t*100);
  const esc = s => String(s ?? '—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cardTitle=(n,t,c='green',badge='LOCKED')=>`<div class="card-title ${c}"><span>🔒</span>${n}. ${t}<span class="badge ${badge==='PENDING'?'pending':badge==='AUTO'?'auto':''}">${badge}</span></div>`;
  const meal=(n,title,color,items)=>`<section class="card meal-card">${cardTitle(n,title,color)}<table><thead><tr><th>食物</th><th>数量</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.food)}</td><td class="center">${esc(x.quantity)}</td></tr>`).join('')}</tbody></table></section>`;
  const hist=d.history;
  const svgLine=(vals,min,max,color='#009b4d')=>{const w=150,h=95,p=16;const xs=vals.map((_,i)=>p+i*(w-2*p)/(vals.length-1));const ys=vals.map(v=>h-p-(v-min)/(max-min)*(h-2*p));return `<svg viewBox="0 0 ${w} ${h}"><polyline points="${xs.map((x,i)=>x+','+ys[i]).join(' ')}" fill="none" stroke="${color}" stroke-width="2"/>${xs.map((x,i)=>`<circle cx="${x}" cy="${ys[i]}" r="3.5" fill="${color}"/><text x="${x}" y="${ys[i]-7}" text-anchor="middle" font-size="9">${vals[i]}</text>`).join('')}</svg>`};
  const workSets=d.training.exercises.flatMap(e=>e.sets.filter(s=>s.type==='working'));
  const duration=(()=>{const [sh,sm]=d.training.start_time.split(':').map(Number),[eh,em]=d.training.end_time.split(':').map(Number);return (eh*60+em)-(sh*60+sm)})();
  const trainingRows=d.training.exercises.map((e,ei)=>{
    const rows=e.sets.map((s,si)=>`<tr>${si===0?`<td rowspan="${e.sets.length}" class="group-cell">${ei+1}</td><td rowspan="${e.sets.length}">${esc(e.name)}</td>`:''}<td>${s.type==='warmup'?'热身':`工作组${e.sets.slice(0,si+1).filter(x=>x.type==='working').length}`}</td><td class="center">1</td><td class="center">${s.reps}</td><td class="center">${s.weight_kg}</td><td class="center">${s.rpe??'—'}</td><td>${esc(s.note)}</td></tr>`).join(''); return rows;
  }).join('');
  const morningRows=[
    ['空腹体重',`${d.morning_check.weight_kg.toFixed(1)} kg`,'正常波动'],['空腹腰围',`${d.morning_check.waist_cm.toFixed(1)} cm`,'良好'],['睡眠时长',fmtMin(d.sleep.sleep_minutes),'良好'],['睡眠效率',`${d.sleep.efficiency_percent}%`,'优秀'],['睡眠评分',`${d.sleep.score} 分`,'良好'],['静息心率',`${d.sleep.heart_rate_bpm} bpm`,'良好'],['肌肉恢复',d.morning_check.muscle_recovery,'—'],['胃部状态',d.morning_check.stomach_status,'—'],['精神状态',d.morning_check.mental_status,'—'],['训练准备度',`${d.morning_check.training_readiness.toFixed(1)} / 10`,'可以正常训练']
  ];
  const nutritionItems=[['热量 (kcal)',d.nutrition.calories_kcal,d.nutrition.targets.calories_kcal],['蛋白质 (g)',d.nutrition.protein_g,d.nutrition.targets.protein_g],['碳水 (g)',d.nutrition.carbs_g,d.nutrition.targets.carbs_g],['脂肪 (g)',d.nutrition.fat_g,d.nutrition.targets.fat_g]];
  app.innerHTML=`
  <header class="header"><div class="brand">🛡️ | PROJECT TITAN | DAILY DATABASE</div><div class="date">日期：${d.meta.date}（${d.meta.week} ${d.meta.day}）</div><div class="legend">Version ${d.meta.version}（锁定模板） 🟢锁定 | ⭐估算 | 🔵自动计算</div></header>
  <main class="main">
    <div class="col">
      <section class="card">${cardTitle(1,'Morning Check（晨间检查）','green')}<table><thead><tr><th>项目</th><th>今日数据</th><th>对比昨日</th><th>状态</th><th>评价</th></tr></thead><tbody>${morningRows.map(r=>`<tr><td>${r[0]}</td><td class="center">${esc(r[1])}</td><td class="center">—</td><td class="center"><span class="kpi-dot"></span></td><td>${r[2]}</td></tr>`).join('')}</tbody></table></section>
      <section class="card">${cardTitle('','恢复指数（Recovery Index）','green')}<table><thead><tr><th>指标</th><th>权重</th><th>得分（满分）</th><th>百分比</th></tr></thead><tbody>${[['睡眠','25%','23 / 25','92%'],['体重 / 腰围','20%','18 / 20','90%'],['肌肉恢复','30%','27 / 30','90%'],['精神状态','15%','13 / 15','87%'],['胃部状态','10%','9 / 10','90%']].map(r=>`<tr>${r.map(x=>`<td class="center">${x}</td>`).join('')}</tr>`).join('')}<tr><td><b>总分（满分100）</b></td><td></td><td class="center"><b>90 / 100</b></td><td class="center good">优秀</td></tr></tbody></table></section>
      <section class="card">${cardTitle('','趋势追踪（体重 & 腰围）','green')}<table><thead><tr><th>日期</th><th>体重 (kg)</th><th>变化</th><th>腰围 (cm)</th><th>变化</th><th>备注</th></tr></thead><tbody>${hist.map((x,i)=>`<tr><td>${x.date}</td><td class="center">${x.weight_kg.toFixed(1)}</td><td class="center">${i? (x.weight_kg-hist[i-1].weight_kg).toFixed(1):'—'}</td><td class="center">${x.waist_cm.toFixed(1)}</td><td class="center">${i?(x.waist_cm-hist[i-1].waist_cm).toFixed(1):'—'}</td><td>睡眠 ${fmtMin(x.sleep_minutes)}</td></tr>`).join('')}</tbody></table><div class="chart-row"><div><div class="spark-title">体重趋势 (kg)</div><div class="spark">${svgLine(hist.map(x=>x.weight_kg),69,73)}</div></div><div><div class="spark-title">腰围趋势 (cm)</div><div class="spark">${svgLine(hist.map(x=>x.waist_cm),75,77)}</div></div></div></section>
      <section class="card">${cardTitle('','数据库进度（Database Progress）','blue')}<div>${Object.entries(d.database_progress).map(([k,v],i)=>`<div class="progress-row"><b>${k}</b><span class="center">🔒 ${v}</span><span class="center">${Math.min(i+3,7)} / 7</span><div class="bar"><span style="width:${Math.min((i+3)/7*100,100)}%"></span></div></div>`).join('')}</div><div class="overall">总体完成度：6 / 7（86%）</div></section>
    </div>
    <div class="col">
      <section class="card">${cardTitle('','Sleep（睡眠记录）','blue')}<div class="sleep-wrap"><div><div class="small">睡眠效率</div><div class="big">${d.sleep.efficiency_percent}%</div><div class="small">合理范围：85% - 100%</div></div><div class="donut"><div class="donut-label">${fmtMin(d.sleep.sleep_minutes)}</div></div><div class="legend-list"><div><span class="sw" style="background:#32118f"></span>深睡　${fmtMin(d.sleep.deep_minutes)}（${Math.round(d.sleep.deep_minutes/d.sleep.sleep_minutes*100)}%）</div><div><span class="sw" style="background:#7650ff"></span>浅睡　${fmtMin(d.sleep.light_minutes)}（${Math.round(d.sleep.light_minutes/d.sleep.sleep_minutes*100)}%）</div><div><span class="sw" style="background:#b4a8ff"></span>REM　${fmtMin(d.sleep.rem_minutes)}（${Math.round(d.sleep.rem_minutes/d.sleep.sleep_minutes*100)}%）</div><div><span class="sw" style="background:#ff7a00"></span>清醒　${d.sleep.awake_minutes}m</div></div></div><div class="sleep-mini"><div class="mini"><strong>${fmtMin(d.sleep.time_in_bed_minutes)}</strong>卧床时长</div><div class="mini"><strong>${fmtMin(d.sleep.sleep_minutes)}</strong>实际睡眠</div><div class="mini"><strong>${d.sleep.awakenings}次</strong>清醒次数</div><div class="mini"><strong>${d.sleep.score}分</strong>睡眠质量评分</div></div><div class="note-box">睡眠平均心率：${d.sleep.heart_rate_bpm}次/分　　睡眠呼吸率：${d.sleep.respiratory_rate}次/分</div></section>
      <div class="meal-grid">${meal(2,'Breakfast（早餐记录）','orange',d.meals.breakfast)}${meal(3,'Lunch（午餐记录）','red',d.meals.lunch)}</div>
      ${meal(5,'Dinner（晚餐记录）','red',d.meals.dinner)}
      <section class="card">${cardTitle('','Today Nutrition（全天营养累计）','blue','AUTO')}<div>${nutritionItems.map(([name,v,t],i)=>`<div class="nutrition-row"><b>${name}</b><span>~${v}</span><span>${t}</span><span>${pct(v,t)}%</span><div class="bar ${pct(v,t)>100?'red':'blue'}"><span style="width:${Math.min(pct(v,t),100)}%"></span></div><span>${v<=t?'~'+(t-v):'+'+(v-t)}</span></div>`).join('')}</div><div class="note-box">备注：营养数据为估算值，后续餐饮摄入后自动更新。</div></section>
      <section class="card"><div class="card-title blue">⚓ 今日营养分布（能量占比）<span class="badge auto">AUTO</span></div><div class="pie-row"><div class="ring" style="--p:26;--c:#0b63ff"><b>26%</b></div><div class="ring" style="--p:42;--c:#7650ff"><b>42%</b></div><div class="ring" style="--p:32;--c:#ff7a00"><b>32%</b></div></div></section>
    </div>
    <div class="col">
      <section class="card training">${cardTitle(4,'Training（训练记录）','red')}<div class="training-meta"><span>训练开始：${d.training.start_time}</span><span>训练结束：${d.training.end_time}</span><span>总时长：${Math.floor(duration/60)}h${duration%60}m</span></div><table><thead><tr><th>项目</th><th>训练内容</th><th>动作</th><th>组数</th><th>次数</th><th>重量</th><th>RPE</th><th>备注</th></tr></thead><tbody>${trainingRows}</tbody></table><div class="note-box">备注：${d.training.body_parts.join(' + ')}训练完成，正式工作组 ${workSets.length} 组。</div></section>
      <section class="card summary">${cardTitle(6,'Daily Summary（每日总结）','red','PENDING')}<table><thead><tr><th>项目</th><th>内容</th></tr></thead><tbody>${Object.entries(d.daily_summary).map(([k,v])=>`<tr><td>${({training:'今日训练完成情况',diet:'今日饮食完成情况',body:'身体状态总结',tomorrow:'明日计划 / 调整'})[k]||k}</td><td>${esc(v)}</td></tr>`).join('')}</tbody></table></section>
      <section class="card summary">${cardTitle(7,'今日关键发现（Discovery）','red','PENDING')}<table><thead><tr><th>类别</th><th>内容</th></tr></thead><tbody>${Object.entries(d.discovery).map(([k,v])=>`<tr><td>${({training:'训练表现',diet:'饮食反馈',body:'身体反馈'})[k]||k}</td><td>${esc(v)}</td></tr>`).join('')}</tbody></table></section>
      <section class="card">${cardTitle(8,'备注（可随时补充）','red','PENDING')}<div class="empty">⌛ ${d.notes??'等待补充'}</div></section>
    </div>
  </main><footer class="footer">所有时间均基于柏林本地时间（CET / CEST），每日数据当日录入，周日晚统一审计汇总。</footer>`;
})();
